import { AggregateRoot, EntityProps } from '../../src/base';
import { AbstractDomainEvent } from '../../src/events';

interface TransactionAggregateProps extends EntityProps {}

class BalanceChangedEvent extends AbstractDomainEvent<{
  previousBalance: number;
  currentBalance: number;
}> {
  constructor(input: { aggregateId: string; previousBalance: number; currentBalance: number }) {
    super({
      type: 'account.balance.changed',
      aggregateType: 'Account',
      aggregateId: input.aggregateId,
      payload: {
        previousBalance: input.previousBalance,
        currentBalance: input.currentBalance,
      },
      metadata: {},
    });
  }
}

class MonthChangedEvent extends AbstractDomainEvent<{
  previousMonth: string;
  currentMonth: string;
}> {
  constructor(input: { aggregateId: string; previousMonth: string; currentMonth: string }) {
    super({
      type: 'transaction.month.changed',
      aggregateType: 'Transaction',
      aggregateId: input.aggregateId,
      payload: {
        previousMonth: input.previousMonth,
        currentMonth: input.currentMonth,
      },
      metadata: {},
    });
  }
}

class TransactionAggregateForTest extends AggregateRoot<TransactionAggregateForTest, TransactionAggregateProps> {
  constructor(
    private readonly transactionId: string,
    private month: string,
    private balance: number,
  ) {
    super({ id: transactionId });
  }

  update(data: { month?: string; balance?: number }) {
    const nextMonth = data.month ?? this.month;
    const nextBalance = data.balance ?? this.balance;

    if (nextMonth !== this.month) {
      this.addEvent(
        new MonthChangedEvent({
          aggregateId: this.transactionId,
          previousMonth: this.month,
          currentMonth: nextMonth,
        }),
      );
    }

    if (nextBalance !== this.balance) {
      this.addEvent(
        new BalanceChangedEvent({
          aggregateId: this.transactionId,
          previousBalance: this.balance,
          currentBalance: nextBalance,
        }),
      );
    }

    this.month = nextMonth;
    this.balance = nextBalance;
  }
}

describe('Event flow integration (AbstractDomainEvent + AggregateRoot)', () => {
  test('should accumulate domain events generated by aggregate mutations and return them in order', () => {
    const aggregate = new TransactionAggregateForTest('550e8400-e29b-41d4-a716-446655440999', '2026-03', 1000);

    aggregate.update({
      month: '2026-04',
      balance: 1300,
    });

    expect(aggregate.hasEvents()).toBe(true);

    const pendingBeforePull = aggregate.peekEvents();
    expect(pendingBeforePull).toHaveLength(2);
    expect(pendingBeforePull[0]?.type).toBe('transaction.month.changed');
    expect(pendingBeforePull[1]?.type).toBe('account.balance.changed');

    const pulledEvents = aggregate.pullEvents();

    expect(pulledEvents).toHaveLength(2);
    expect(pulledEvents[0]?.type).toBe('transaction.month.changed');
    expect(pulledEvents[0]?.payload).toEqual({
      previousMonth: '2026-03',
      currentMonth: '2026-04',
    });
    expect(pulledEvents[1]?.type).toBe('account.balance.changed');
    expect(pulledEvents[1]?.payload).toEqual({
      previousBalance: 1000,
      currentBalance: 1300,
    });

    expect(aggregate.hasEvents()).toBe(false);
    expect(aggregate.peekEvents()).toEqual([]);
  });

  test('should not generate events when no relevant state changes happen', () => {
    const aggregate = new TransactionAggregateForTest('550e8400-e29b-41d4-a716-446655440998', '2026-03', 1000);

    aggregate.update({
      month: '2026-03',
      balance: 1000,
    });

    expect(aggregate.hasEvents()).toBe(false);
    expect(aggregate.pullEvents()).toEqual([]);
  });
});
